name: ebogne_transfert
description: Une application de transfert d'argent
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Cette section DOIT être alignée à la racine (tout à gauche)
flutter:
  uses-material-design: true

  # Attention à l'indentation ici (2 espaces)
  assets:
    - assets/images/  # Ajout de l'espace après le tiret et du slash final